CREATE TABLE IF NOT EXISTS courts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  club_id INT NOT NULL,
  name VARCHAR(50),
  rtsp_url VARCHAR(255),
  FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE CASCADE
);