ALTER TABLE clubs
ADD COLUMN country VARCHAR(255) NULL,
ADD COLUMN province VARCHAR(255) NULL,
ADD COLUMN city VARCHAR(255) NULL,
ADD COLUMN address VARCHAR(255) NULL,
ADD COLUMN description TEXT NULL,
ADD COLUMN phone VARCHAR(50) NULL,
ADD COLUMN instagram_handle VARCHAR(100) NULL;
