ALTER TABLE users
  ADD COLUMN system_role ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER',
  ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN token_version INT NOT NULL DEFAULT 0,
  ADD COLUMN totp_secret TEXT NULL,
  ADD COLUMN totp_enabled TINYINT(1) NOT NULL DEFAULT 0;
